/**
 * @module tutors.service.ts
 * @description Tutor invite flow and interactive web form for teacher responses.
 *
 *              The problem: Teachers teach 100+ students. They will NOT download
 *              a special app just for 2 students. Solution: Email + 30-second web form.
 *
 *              Flow:
 *              1. Parent taps "Invite Tutor" → enters tutor's email
 *              2. AI generates 3-5 targeted questions based on parent's concern
 *              3. System emails tutor a branded, mobile-friendly link
 *              4. Tutor clicks link → one-page web form (no login required)
 *              5. Tutor answers in 20-30 seconds → clicks Submit
 *              6. Parent receives notification with AI-summarized tutor report
 */

import { Injectable, NotFoundException, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as jwt from 'jsonwebtoken';
import { Resend } from 'resend';
import { v4 as uuidv4 } from 'uuid';
import { PrismaService } from '../../database/prisma.service';
import { NotificationsService } from '../notifications/notifications.service';
import { AiService } from '../ai/ai.service';
import { NotificationType } from '@parentingmykid/shared-types';
import { IsString, IsBoolean, IsOptional, IsArray } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class InviteTutorDto {
  @ApiProperty()
  @IsString()
  childId!: string;

  @ApiProperty()
  @IsString()
  tutorEmail!: string;

  @ApiProperty({ required: false })
  @IsOptional()
  @IsString()
  tutorName?: string;

  @ApiProperty({ description: 'Parent\'s concern for the AI question generator' })
  @IsString()
  concern!: string;

  @ApiProperty({ default: true })
  @IsOptional()
  @IsBoolean()
  scopeAcademic?: boolean;

  @ApiProperty({ default: true })
  @IsOptional()
  @IsBoolean()
  scopeBehavior?: boolean;
}

export class SubmitTutorResponseDto {
  @ApiProperty({ type: 'array' })
  @IsArray()
  responses!: Array<{ questionId: string; rating?: number; text?: string }>;
}

@Injectable()
export class TutorsService {
  private readonly logger = new Logger(TutorsService.name);
  private readonly resend: Resend;

  constructor(
    private readonly prisma: PrismaService,
    private readonly notifications: NotificationsService,
    private readonly aiService: AiService,
    private readonly config: ConfigService,
  ) {
    this.resend = new Resend(config.get<string>('RESEND_API_KEY'));
  }

  /**
   * Creates a tutor invite and sends the branded email with web form link.
   * Questions are generated by AI based on the parent's concern.
   */
  async inviteTutor(parentId: string, dto: InviteTutorDto) {
    const child = await this.prisma.childProfile.findFirst({
      where: { id: dto.childId, parentId },
    });
    if (!child) throw new NotFoundException('Child not found');

    const age = new Date().getFullYear() - new Date(child.dob).getFullYear();

    // Generate AI questions
    const questions = await this.aiService.generateTutorQuestions(
      dto.concern,
      child.name,
      age,
    );

    // Generate short-lived JWT token for the tutor web form
    const jwtSecret = this.config.getOrThrow<string>('JWT_SECRET');
    const token = jwt.sign(
      { inviteId: 'placeholder', childId: dto.childId, parentId },
      jwtSecret,
      { expiresIn: '72h' },
    );

    const tokenExpiresAt = new Date(Date.now() + 72 * 60 * 60 * 1000);

    // Create invite record
    const invite = await this.prisma.tutorInvite.create({
      data: {
        childId: dto.childId,
        parentId,
        tutorEmail: dto.tutorEmail,
        tutorName: dto.tutorName,
        scopeAcademic: dto.scopeAcademic ?? true,
        scopeBehavior: dto.scopeBehavior ?? true,
        token,
        tokenExpiresAt,
        questionsJson: questions,
      },
    });

    // Send email to tutor
    const webFormUrl = `${this.config.get('APP_URL')}/api/v1/tutors/respond/${token}`;

    await this.sendTutorEmail(dto.tutorEmail, dto.tutorName ?? 'Teacher', child.name, webFormUrl, questions);

    this.logger.log(`Tutor invite sent to ${dto.tutorEmail} for child ${child.name}`);

    return invite;
  }

  /**
   * Returns the public web form page (no auth required — accessed via email link).
   * Token is short-lived (72h) and single-use.
   */
  async getTutorForm(token: string) {
    const invite = await this.prisma.tutorInvite.findUnique({ where: { token } });

    if (!invite || invite.status !== 'PENDING') {
      throw new NotFoundException('This form has already been submitted or has expired.');
    }

    if (new Date() > invite.tokenExpiresAt) {
      throw new NotFoundException('This link has expired. Please ask the parent to send a new invite.');
    }

    const child = await this.prisma.childProfile.findUniqueOrThrow({
      where: { id: invite.childId },
    });

    return {
      childName: child.name,
      tutorName: invite.tutorName ?? 'Teacher',
      questions: invite.questionsJson,
    };
  }

  /**
   * Tutor submits their responses via the web form (no login required).
   * AI summarizes the responses and notifies the parent immediately.
   */
  async submitTutorResponse(token: string, dto: SubmitTutorResponseDto) {
    const invite = await this.prisma.tutorInvite.findUnique({
      where: { token },
      include: { child: true, parent: true },
    });

    if (!invite) throw new NotFoundException('Invalid form link');

    // Update the invite with responses
    await this.prisma.tutorInvite.update({
      where: { token },
      data: {
        responsesJson: dto.responses,
        status: 'RESPONDED',
        respondedAt: new Date(),
      },
    });

    // Notify parent
    await this.notifications.sendToUser(invite.parentId, {
      type: NotificationType.TUTOR_RESPONSE,
      title: `📝 ${invite.tutorName ?? 'Your tutor'} responded!`,
      body: `${invite.child.name}'s tutor answered your questions. Tap to see the report.`,
      data: { screen: 'tutors', inviteId: invite.id, childId: invite.childId },
      priority: 'default',
    });

    return { success: true, message: 'Thank you! Your response has been sent to the parent.' };
  }

  private async sendTutorEmail(
    tutorEmail: string,
    tutorName: string,
    childName: string,
    formUrl: string,
    questions: Array<{ id: string; text: string; type: string }>,
  ): Promise<void> {
    const questionList = questions
      .map((q, i) => `<li style="margin-bottom: 8px;">${i + 1}. ${q.text}</li>`)
      .join('');

    await this.resend.emails.send({
      from: this.config.get<string>('EMAIL_FROM', 'noreply@parentingmykid.com'),
      to: tutorEmail,
      subject: `Quick question about ${childName} — 30 seconds needed`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #f8f7ff; padding: 20px; border-radius: 16px;">
          <div style="background: linear-gradient(135deg, #6366F1, #8B5CF6); padding: 30px; border-radius: 12px; text-align: center; margin-bottom: 24px;">
            <h1 style="color: white; margin: 0; font-size: 24px;">ParentingMyKid</h1>
            <p style="color: rgba(255,255,255,0.8); margin: 8px 0 0;">Family Growth Platform</p>
          </div>
          
          <h2 style="color: #1e1e2e; margin-bottom: 8px;">Hello ${tutorName}!</h2>
          
          <p style="color: #475569; line-height: 1.6; margin-bottom: 16px;">
            ${childName}'s parent uses ParentingMyKid to help ${childName} grow academically 
            and personally. They have a few quick questions about ${childName}'s progress.
          </p>
          
          <p style="color: #475569; font-weight: bold; margin-bottom: 12px;">Questions about ${childName}:</p>
          <ul style="color: #475569; line-height: 1.8; margin-bottom: 24px; padding-left: 20px;">
            ${questionList}
          </ul>
          
          <p style="color: #475569; margin-bottom: 16px;">
            This will take just <strong>20-30 seconds</strong> — no account needed, 
            just click the button below and answer directly in your browser.
          </p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="${formUrl}" style="background: #6366F1; color: white; text-decoration: none; padding: 16px 32px; border-radius: 12px; font-weight: bold; font-size: 16px; display: inline-block;">
              Answer Questions (30 seconds)
            </a>
          </div>
          
          <p style="color: #94A3B8; font-size: 12px; text-align: center; margin-top: 24px;">
            This link expires in 72 hours. If you have questions, please contact ${childName}'s parent directly.
          </p>
        </div>
      `,
    });
  }
}
